### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ElPumpo** [ElPumpo/TinyNvidiaUpdateChecker#14]
# Currect todo focus
- [ ] ~~Ditch HTMLAglityPack, as it is incompatible with GPLv3 (Ms-Pl) code (??) and depending on libaries makes the application feel jerky~~ Seems like they moved to the MIT license (yey), and I'm keeping it.
    - [ ] ~~replace with regex, shouldn't be that difficult~~
    - [ ] ~~remove traces from all project files~~
    - [x] _OR_... keep using it for future AMD and Intel GPU support
- [x] Finish making installer code (option to it on or off)
    - [x] option to disable it if WinRAR isn't found
- [ ] Improve GPU detection code
    - [ ] improve handling if gpu name from config isn't found
    - [ ] test if gpu version number has the correct length
----
# Future things todo
- [ ] Self-updater
- [ ] Replace with GUI
    - [ ] Make TinyNvidiaUpdateChecker a libary instead of a executable.
        - [ ] Create new Project, TinyGPUUpdateChecker that will be the core, and will require libaries
            - [ ]  libaries will output a `offlinever`, `onlinever`, a URL to the latest driver, a URL to the full changelog, and brief desc of driver for the manufacturer, for example `TinyNvidiaUpdateChecker.dll`, `TinyAMDUpdateChecker.dll` and `TinyIntelUpdateChecker.dll`.
            - [ ] libaries will be responsible for the above, leaving the core to handle GUI and notifications.
        - [ ] Add support for AMD GPUs
        - [ ] Add support for Intel GPUs

**Comment by fyr77** [comment]
Maybe my project EnvyUpdate can help you with your todo here. Check my code: https://github.com/fyr77/EnvyUpdate
There's still a few things I'd like to clean up and add myself, but I think I got some things that _might_ help you.

**Comment by ElPumpo** [comment]
Sup @fyr77, and thanks for the shoutout in your project! This project is really on its EOL, as I'm not into development anymore. Lol development turned out to not be my thing at all, but thanks anyways

**Comment by fyr77** [comment]
Ah, I see. Good luck then in whatever you're doing!

Let's see, maybe I'll fork this when I have some spare time.
